### ISSUE TITLE
darwin: fork/exec bootstrap.sh: operation not permitted

### ISSUE THREAD

**Issue by rvl** [buildkite/agent#661]
Running buildkite-agent v2.6.9 on Mac OS X 10.11.6, I am getting the following error when running a job:

    fork/exec /nix/store/gxbgiab4wfv1k504grcn9vhgccgv84gk-buildkite-agent-2.6.9-bin/libexec/buildkite-agent/bootstrap.sh: operation not permitted

If I click "Retry" on the web interface, the job will run successfully. Subsequent jobs will run successfully, until the daemon is restarted.

I have collected logs and config files in [a gist](https://gist.github.com/rvl/9ef554bee841663f9694f44791ab2770).

This is a screenshot of the web interface:

![buildkite-darwin](https://user-images.githubusercontent.com/1019641/36734410-547250b8-1bcb-11e8-8dd0-01e85fa9761e.png)

I have tried playing with the `OnDemand` and `SessionCreate` options in the launchd daemon plist, so that it's the same as [templates/launchd.plist](https://github.com/buildkite/agent/blob/master/templates/launchd.plist).

Do you know why it could be failing?

**Comment by lox** [comment]
That's an odd one @rvl, apologies. I'm assuming that bootstrap.sh has execute permissions set?

Failing that, I actually ran into a thread from @keithpitt in '15: https://forum.golangbridge.org/t/setpgid-pty-operation-not-permitted/1225/33

I'll check that we have the latest version of `kr/pty` in the agent, but you could verify this by setting `no-pty` in your buildkite-agent.cfg (https://buildkite.com/docs/agent/configuration).

**Comment by rvl** [comment]
Thanks @lox. Adding `no-pty=true` seems to have fixed the problem.

**Comment by lox** [comment]
That's great, we'll try and get an updated version of the pty library into the next release.

The v3 agent will be marked stable very soon if you feel inclined to go that way!

**Comment by rvl** [comment]
Thanks. Is it possible that `no-pty=true` has other effects? For example causing a git fetch to fail? I have just received these errors in the pipeline upload step.

```
buildkite-agent pipeline upload
2018-03-08 08:34:33 WARN   POST https://agent.buildkite.com/v3/jobs/c3fe23b8-c7e1-4ad2-8442-ae5e94626827/pipelines: 422 Configuration is empty (Attempt 1/5 Retrying in 1s)
2018-03-08 08:34:39 FATAL  Failed to upload and process pipeline: POST https://agent.buildkite.com/v3/jobs/c3fe23b8-c7e1-4ad2-8442-ae5e94626827/pipelines: 422 Configuration is empty
```

**Comment by lox** [comment]
It shouldn't affect that @rvl, no. That said, I've seen that error reported recently. If you continue to see this, could I trouble you to lodge a new bug with the above error?

**Comment by keithpitt** [comment]
After a little bit of digging, I think we tracked it down to swallowing this error here: https://github.com/buildkite/agent/blob/2-6-stable/api/pipelines.go#L46

Possible an "out of disk" error where we can't write the temporary file, but it's resulting in a weird error message. Will sneak out a patch to stable to fix this now.

**Comment by keithpitt** [comment]
Fixed here: https://github.com/buildkite/agent/commit/ce612fc8406f7de031c671478c380cedf4399700

Will push out a new stable version of the agent now!

**Comment by rvl** [comment]
Thanks @lox @keithpitt for the help and fixes.

I have just tried v2.6.10 with the updated `github.com/kr/pty` dep and pipeline upload fix.

From what I can see, both the original "fork/exec" issue and the `422 Configuration is empty` error remain.

I can choose between the two errors by using the `no-pty` option.

The Buildkite web interface reports that the agent is running v2.6.10. There is plenty of free disk space. Is it possible that the temporary file is being created in a read-only location?
